// <auto-generated />
namespace Survey_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Use : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Use));
        
        string IMigrationMetadata.Id
        {
            get { return "202002120925289_Use"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
